server:
  port: 8089

sso:
  dingtalk:
    client-id: xxx
    client-secret: xxx
    agent-id: 000
    corp-id: xxx
    redirect-uri: http://your-app.com/callback
  wechat:
    agent-id: xxx
    client-id: xxx
    client-secret: xxxx
    redirect-uri: http://your-app.com/callback
  feishu:
    client-id: xxxx
    client-secret: xxxxxx
    redirect-uri: http://your-app.com/callback

